version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    volumes:
      - /root/astra-star-fe/.env:/app/.env  # Ganti dengan jalur ke file .env di VPS Anda
    environment:
      NODE_ENV: production  # Anda bisa menambahkan variabel lingkungan lain di sini
