name: Next.js CI/CD

on:
  push:
    branches: [ dev ] # Mengubah branch target menjadi main atau sesuaikan dengan branch yang Anda gunakan
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.1' # Spesifikasi versi Node.js
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js project
        run: npm run build # Memastikan Anda memiliki script "build" di package.json

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build . -t ${{ secrets.DOCKER_USERNAME }}/astra-star-fe:${IMAGE_TAG}
          docker push ${{ secrets.DOCKER_USERNAME }}/astra-star-fe:${IMAGE_TAG}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/astra-star-fe:${{ github.sha }}
            docker stop astra-star-fe || true
            docker rm astra-star-fe || true
            docker run -d --name astra-star-fe -p 8086:8086 -v /root/astra-star-fe/.env:/home/node/app/.env ${{ secrets.DOCKER_USERNAME }}/astra-star-fe:${{ github.sha }}
